title: # a name for your Learning Lab course
tagline: # a short description for your Learning Lab course, displayed on the course catalog
description: # a longer description for your Learning Lab course, displayed on the course's landing page

# Repository setup
# The following section template information for the repository
# This will be used when the repository is crated for each individual learner

template:
  name: # the name of the repository when it is created for the learner
  repo: # the name of the template repository from which to clone for the learner

# `before` block
# Actions to take place after the learner registers, but before they start interacting with their repo

before:
- type: # the type of action, full list at https://lab.github.com/docs/actions/
  # some actions require additional options, those should appear below `type:`
  # you can execute multiple actions in the `before` block

# Steps for the course
# A list of steps that take the learner through the course
# Create one step for each action that a learner will complete

steps:
# Step 1: Create a task list 
- title: # Create a task list
  description: # 1a description of the step, shown to the learner in the course progress page
  event: # the event that will trigger the actions to be executed, full list at https://developer.github.com/v3/activity/events/types/
  actions: # a list of the actions that will occur when the step is triggered by an event
  - type: # the type of action, full list at https://lab.github.com/docs/actions

# Step 2: Turn on GitHub Pages
# - title: # Turn on GitHub Pages
#  description: # 2a description of the step, shown to the learner in the course progress page
#  event: # the event that will trigger the actions to be executed, full list at https://developer.github.com/v3/activity/events/types/
#  actions: # a list of the actions that will occur when the step is triggered by an event
#  - type: # the type of action, full list at https://lab.github.com/docs/actions

# Step 3: Add headers
# - title: # Add headers
#  description: # 3a description of the step, shown to the learner in the course progress page
#  event: # the event that will trigger the actions to be executed, full list at https://developer.github.com/v3/activity/events/types/
#  actions: # a list of the actions that will occur when the step is triggered by an event
#  - type: # the type of action, full list at https://lab.github.com/docs/actions

# Step 4: Merge your headers
# - title: # Merge your headers
#  description: # 4a description of the step, shown to the learner in the course progress page
#  event: # the event that will trigger the actions to be executed, full list at https://developer.github.com/v3/activity/events/types/
#  actions: # a list of the actions that will occur when the step is triggered by an event
#  - type: # the type of action, full list at https://lab.github.com/docs/actions

# Step 5: 5EDIT HERE - INTERNAL COMMENT FOR STEP 5
# - title: # 5the title of the step, shown to the learner in the course progress page
#  description: # 5a description of the step, shown to the learner in the course progress page
#  event: # the event that will trigger the actions to be executed, full list at https://developer.github.com/v3/activity/events/types/
#  actions: # a list of the actions that will occur when the step is triggered by an event
#  - type: # the type of action, full list at https://lab.github.com/docs/actions

